name: mapbox/python-cpp-skel
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.6', '3.7']
        env: ['CC="gcc" CXX="g++"', 'CC="clang" CXX="clang++"', 'CXX="g++-6" CC="gcc-6" LINK="g++-6" AR="ar" NM="nm"']

    steps:
      - uses: actions/checkout@v4
      - name: Enable c++11/14 builds
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt-get install -y libstdc++-4.9-dev libstdc++-6-dev g++-6
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip installs
        run: |
          pip install pytest
          pip install --verbose .
      - name: Run tests
        run: |
          ${{ matrix.env }} pytest
